language: node_js
node_js:
 - "node"
services:
 - xvfb
script:
 - npm test
 - npm run test-int
 - npm run test-e2e
 - npm run eslint
after_success:
 - npm run coveralls
before_cache:
 - rm -rf $HOME/build/nkl-kst/MagicMirror/modules/MMM-RBB-Weather
cache:
 directories:
  - node_modules
  - $HOME/build/nkl-kst/MagicMirror
